name: Main Workflow
on: [workflow_dispatch]
jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run local k6 test
        uses: k6io/action@v0.2.0
        with:
          # filename: test/perf/*.js
          flags: --vus 1000 --duration 5m
          cloud: true
          token: ${{ secrets.K6_CLOUD_API_TOKEN }}